baseURL = "https://example.com"
title = "Your title"
themesDir = "../.."
theme = "m10c"
paginate = 8

[params]
  author = "Anupam Singh"
  description = "An average security guy"
  [menu]
  [[menu.main]]
    identifier = "Hackerone"
    name = "Hackerone"
    url = "https://Hackerone.com/AnupaAS01"
    weight = 1
  [[menu.main]]
    identifier = "Bugcrowd"
    name = "Bugcrowd"
    url = "https://Bugcrowd.com/AnupaAS01"
    weight = 2
  [[menu.main]]
    identifier = "Intigriti"
    name = "Intigriti"
    url = "https://app.intigriti.com/profile/anupamas/"
    weight = 3